### PR TITLE
File type detection & Excel support

### LINKED ISSUE #58: Check to restrict filetypes permitted
### Summary
I managed to import an HTML document into Dataproofer which it then interpreted as a spreadsheet and spat out irrelevant stats. Dataset was the HTML of the front page of Hacker News
[(attached)](https://github.com/dataproofer/Dataproofer/files/192615/Hacker.News.html.zip). I did this on OS X 10.11.4 but OS/Version shouldn't really matter.
### Steps to reproduce
Import attached XML document into Dataproofer.
### Expected behavior
Maybe tell me that the data type is unsupported or at least don't run stats on what is clearly not a valid dataset.
### Relevant logs and/or screenshots
screen shot 2016-03-28 at 6 16 53 pm
### Possible fixes?
Be especially suspicious of a dataset with a single column. Maybe pop up a warning asking the user if they are sure that this is what they want to do.
### Related issues/pull requests?
None that I am aware of. I doubt that this was introduced from a pull request -- just seems to be an edge case that may not have been handled.

UPDATE: This seems to work on binary data as well, I imported images and zip files successfully into Dataproofer which should not happen.

Thanks!

### PR DESCRIPTION
**Pull request by geraldarthur**
Fixes #58 #63

**Summary**

Adds filetype support and alerts the user if an invalid filetype is uploaded. Dataproofer now accepts:
* xlsx
* xls
* csv
* tsv
* psv

**Proposed changes**

* What was added:
  * more test files to test different filetypes
* What was modified:
  * controller.js: detects file extensions. mime-types were less reliable when it came to more esoteric separated values like "psv".
  * processing.js: handles files based upon their file extensions
  * code style editing for consistency leading up to official launch 

cc @dataproofer/core

### CODE REVIEW

File: electron/js/controller.js [hunk 1]
```diff
@@ -1,29 +1,22 @@
...
-var ipc = require("electron").ipcRenderer
-
+var d3 = require("d3");
+var Processor = require("dataproofer").Processing;
+var gsheets = require("gsheets");
+var ipc = require("electron").ipcRenderer;
 
 // libraries required to run test inline
-var requireFromString = require('require-from-string')
+// var requireFromString = require("require-from-string");
```
Comment (enjalot) [inline electron/js/controller.js]: is this commented out on purpose? this is used for running local tests

Comment (enjalot) [inline electron/js/controller.js]: my bad, i think i tried using it and decided against it later. we should delete... oops :)

File: electron/js/controller.js [hunk 2]
```diff
@@ -351,52 +340,69 @@ function clear() {
...
 
 // This handles file selection via the button
-document.getElementById('file-loader').addEventListener('change', handleFileSelect, false);
+document.getElementById("file-loader").addEventListener("change", handleFileSelect, false);
+
 function handleFileSelect(evt) {
-  var files = evt.target.files
+  var files = evt.target.files;
   if(!files || !files.length) return;
   for(var i = 0, f; i < files.length; i++) {
```
Comment (enjalot) [inline electron/js/controller.js]: this is actually an old bug, but we have set ourselves up for a scope trap here. Below we have an async call within a for loop, bad news!
not only that, but we don't really support loading multiple files. I'm pretty sure the file input only allows you to load 1 anyway, but this is kind of a trap for the future where we may want to let people run multiple datasets for some reason.

**Comment by enjalot** [comment]
this is awesome, great job @geraldarthur!! :100:
